### ISSUE TITLE
The execution of the project will not only crash in main_ga, but also hang midway in other scripts such as main_baseline

### ISSUE THREAD

**Issue by lilejin322** [YuqiHuai/DoppelTest#5]
Sorry for the bothering again. We've encountered some problems while running this project and don't know how to solve them.

**Describe the issue**

&nbsp;&nbsp;The script [test_main.py](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/test_main.py) can complete execution smoothly due to its single iteration. However, when switching to scripts like [main_baseline.py](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/main_baseline.py) and [main_ga.py,](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/main_ga.py) which require long-running processes, the system appears to be unstable. Specifically, after running the scenario several times, it will eventually crash with a segmentation fault error indicated from the shell.
&nbsp;&nbsp;We’ve diagnosed the project using tools like pdb, but still couldn’t find where does the distinct error come from. The screenshot is shown as follow.

![shell segmentation fault](https://github.com/Software-Aurora-Lab/DoppelTest/assets/40066434/1b95ecde-7602-4408-8edd-2e76d2329fcf)

**Environment**
1. Hardware configuration
CPU: Intel Core i9 14900K (24-core)
Memory: 128GB
Graphic Card: None
2. Software configuration
OS: Ubuntu 18.04
Docker-CE: version 24.0.2
Python: version 3.9.18
3. Requirements to be met in [README.md](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/REQUIREMENTS.MD)

**To reproduce**
1. Run python [main_ga.py](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/main_ga.py)
2. Open the Dreamviews in browser<span id="jump"></span>
3. After several iterations in the Genetic Cycle -> g0s0, g0s1,…, the shell will get stuck
4. From the observation in the browser, it seems that there is a potential system freezing whenever one of the ADCs arrives its destination
5. Dozens of minutes later, the shell reports “Segmentation fault” and the python script exits
6. Command `~$ docker kill $(docker ps -q)`
7. Change the DoppelTest map data to `san_mateo` in [config.py](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/config.py)
8. Update the `{ApolloROOT}/modules/common/data/global_flagfile.txt` as well
9. Run python [main_baseline.py](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/main_baseline.py)
10. Step [2-5](#jump) regenerated

**Current Result**

&nbsp;&nbsp;The script might report an error and exit after running for several generations.

**Expected Result**

&nbsp;&nbsp;The system shall exit normally after a timeout instructed by RUN_FOR_HOUR parameter defined in [config.py](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/config.py).

**Debugging Endeavors**
1. Check if the versions in conda env meet the [requirements.txt](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/requirements.txt)
2. Alter different map asset bundles
3. Force containers to restart on each iteration within the main() by moving the ctn starting code into the While loop
https://github.com/Software-Aurora-Lab/DoppelTest/blob/264a06e6474ae1ffc378521578ead7f43edd08fa/main_baseline.py#L63-L65
4. In [framework/scenario/ScenarioRunner.py](https://github.com/Software-Aurora-Lab/DoppelTest/blob/main/framework/scenario/ScenarioRunner.py), disable all applications of MessageBroker using comment sign `#`
https://github.com/Software-Aurora-Lab/DoppelTest/blob/264a06e6474ae1ffc378521578ead7f43edd08fa/framework/scenario/ScenarioRunner.py#L119-L120
https://github.com/Software-Aurora-Lab/DoppelTest/blob/264a06e6474ae1ffc378521578ead7f43edd08fa/framework/scenario/ScenarioRunner.py#L133
https://github.com/Software-Aurora-Lab/DoppelTest/blob/264a06e6474ae1ffc378521578ead7f43edd08fa/framework/scenario/ScenarioRunner.py#L161

**Comment by YuqiHuai** [comment]
@lilejin322 Hi, this is a very interesting outcome of running DoppelTest and I have never seen this before. Do you have any screenshots displaying the `segmentation fault`?

Also, did the segmentation fault appear in one of the containers?

**Comment by YuqiHuai** [comment]
@lilejin322 Hi! Thank you for providing additional information. The graphics card should not be a problem since I was able to run DoppelTest on a server without a graphics card. Here are some of my thoughts based on this information:

1. Personally, I have not seen a segmentation fault in Python before. What is the hardware specification of your machine? My initial guess would be somehow your machine does not have sufficient memory.

2. The remaining screenshots show the stack trace when you use Ctrl+C to send a `KeyboardInterrupt`, it seems like the problem is around lines involving `subprocess.run`. My suggestion for debugging would be adding an additional log statement before `subprocess.run`, for example, [here](https://github.com/Software-Aurora-Lab/DoppelTest/blob/264a06e6474ae1ffc378521578ead7f43edd08fa/apollo/ApolloContainer.py#L247) and [here](https://github.com/Software-Aurora-Lab/DoppelTest/blob/264a06e6474ae1ffc378521578ead7f43edd08fa/apollo/ApolloContainer.py#L232), to figure out which container is causing DoppelTest to hang, then manually run the command `docker exec ......` in another terminal to see what is going on.

3. It looks like once hanging occurs, you can stop DoppelTest and restart it to reproduce the hanging behavior, and you don't need to run it for another couple of hours to reproduce the issue, is that correct?

I apologize for not being able to directly solve this issue as I have not seen it on all 4 of the machines available to me. If the problem persists, I am happy to talk with you over Zoom and try to figure out the issue on your end 😄

**Comment by YuqiHuai** [comment]
@lilejin322 thanks for providing more details. Looks like the issues is around stop recorder and stop sim control. Your machine does have almost equivalent hardware to one of mine.

the logs you attached, is this just the end of that file when error started occurring?

**Comment by YuqiHuai** [comment]
@lilejin322 It is very unusual to have this kind of error, and this error would prevent scenarios from being generated correctly. Can we setup a Zoom meeting and have me look at the issue on your machine remotely?

**Comment by YuqiHuai** [comment]
@lilejin322 This is consistent with my understanding. SimControl isn't running at all. 

Which Apollo are you using and can you give this https://github.com/YuqiHuai/BaiduApollo/tree/DoppelTest a try?

**Comment by YuqiHuai** [comment]
@lilejin322 That shouldn't have an issue either. Currently, I am not sure what is happening and I'll wait for our meeting to take a closer look.
